import type { Metadata } from "next"
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter"
import Header from "@components/global/header/Header"
import Content from "@components/global/Content"

export const metadata: Metadata = {
  title: "Colored Shapes",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <Header />
          <Content>{children}</Content>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
